import cake from "./Images/cake.jpeg";

export const ProductData = [
  {
    id: 1,
    name: "Black Forest cake",
    desc: "Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for will uncover many web sites still in their infancy. Various versions have evolved over the year",
    price: "50",
    Button: "Add to cart",
    img: cake,
  },
  {
    id: 2,
    name: "Black Forest cake",
    desc: "Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for will uncover many web sites still in their infancy. Various versions have evolved over the year",
    price: "90",
    Button: "Add to cart",
    img: "https://images.unsplash.com/photo-1545696563-af8f6ec2295a?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=385&q=80",
  },
  {
    id: 3,
    name: "Black Forest cake",
    desc: "Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for will uncover many web sites still in their infancy. Various versions have evolved over the year",
    price: "120",
    Button: "Add to cart",
    img: "https://images.unsplash.com/photo-1535141192574-5d4897c12636?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1888&q=80",
  },
  {
    id: 4,
    name: "Black Forest cake",
    desc: "Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for will uncover many web sites still in their infancy. Various versions have evolved over the year",
    price: "30",
    Button: "Add to cart",
    img: "https://images.unsplash.com/photo-1562777717-dc6984f65a63?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=387&q=80",
  },
  {
    id: 5,
    name: "Black Forest cake",
    desc: "Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for will uncover many web sites still in their infancy. Various versions have evolved over the year",
    price: "40",
    Button: "Add to cart",
    img: "https://images.unsplash.com/photo-1542826438-bd32f43d626f?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1292&q=80",
  },
  {
    id: 6,
    name: "Black Forest cake",
    desc: "Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for will uncover many web sites still in their infancy. Various versions have evolved over the year",
    price: "60",
    Button: "Add to cart",
    img: "https://images.unsplash.com/photo-1558301211-0d8c8ddee6ec?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=336&q=80",
  },
  {
    id: 7,
    name: "Black Forest cake",
    desc: "Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for will uncover many web sites still in their infancy. Various versions have evolved over the year",
    price: "80",
    Button: "Add to cart",
    img: "https://images.unsplash.com/photo-1579306194872-64d3b7bac4c2?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1117&q=80",
  },
  {
    id: 8,
    name: "Black Forest cake",
    desc: "Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for will uncover many web sites still in their infancy. Various versions have evolved over the year",
    price: "65",
    Button: "Add to cart",
    img: "https://images.unsplash.com/photo-1562023692-9283c11284bd?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=387&q=80",
  },
  {
    id: 9,
    name: "Black Forest cake",
    desc: "Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for will uncover many web sites still in their infancy. Various versions have evolved over the year",
    price: "75",
    Button: "Add to cart",
    img: "https://images.unsplash.com/photo-1606890737304-57a1ca8a5b62?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=503&q=80",
  },
  {
    id: 10,
    name: "Black Forest cake",
    desc: "Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for will uncover many web sites still in their infancy. Various versions have evolved over the year",
    price: "90",
    Button: "Add to cart",
    img: "https://images.unsplash.com/photo-1582602248706-ddb12de0e625?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=387&q=80",
  },
];

export const ProductData2 = [
  {
    id: 1,
    name: "Black Forest cake",
    desc: "Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for will uncover many web sites still in their infancy. Various versions have evolved over the year",
    price: "50",
    Button: "Add to cart",
    img: cake,
  },
  {
    id: 2,
    name: "Black Forest cake",
    desc: "Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for will uncover many web sites still in their infancy. Various versions have evolved over the year",
    price: "90",
    Button: "Add to cart",
    img: "https://images.unsplash.com/photo-1545696563-af8f6ec2295a?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=385&q=80",
  },
  {
    id: 3,
    name: "Black Forest cake",
    desc: "Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for will uncover many web sites still in their infancy. Various versions have evolved over the year",
    price: "120",
    Button: "Add to cart",
    img: "https://images.unsplash.com/photo-1535141192574-5d4897c12636?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1888&q=80",
  },
  {
    id: 4,
    name: "Black Forest cake",
    desc: "Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for will uncover many web sites still in their infancy. Various versions have evolved over the year",
    price: "30",
    Button: "Add to cart",
    img: "https://images.unsplash.com/photo-1562777717-dc6984f65a63?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=387&q=80",
  },
  {
    id: 5,
    name: "Black Forest cake",
    desc: "Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for will uncover many web sites still in their infancy. Various versions have evolved over the year",
    price: "40",
    Button: "Add to cart",
    img: "https://images.unsplash.com/photo-1542826438-bd32f43d626f?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1292&q=80",
  },
  {
    id: 6,
    name: "Black Forest cake",
    desc: "Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for will uncover many web sites still in their infancy. Various versions have evolved over the year",
    price: "60",
    Button: "Add to cart",
    img: "https://images.unsplash.com/photo-1558301211-0d8c8ddee6ec?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=336&q=80",
  },
  {
    id: 7,
    name: "Black Forest cake",
    desc: "Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for will uncover many web sites still in their infancy. Various versions have evolved over the year",
    price: "80",
    Button: "Add to cart",
    img: "https://images.unsplash.com/photo-1579306194872-64d3b7bac4c2?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1117&q=80",
  },
  {
    id: 8,
    name: "Black Forest cake",
    desc: "Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for will uncover many web sites still in their infancy. Various versions have evolved over the year",
    price: "65",
    Button: "Add to cart",
    img: "https://images.unsplash.com/photo-1562023692-9283c11284bd?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=387&q=80",
  },
  {
    id: 9,
    name: "Black Forest cake",
    desc: "Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for will uncover many web sites still in their infancy. Various versions have evolved over the year",
    price: "75",
    Button: "Add to cart",
    img: "https://images.unsplash.com/photo-1606890737304-57a1ca8a5b62?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=503&q=80",
  },
  {
    id: 10,
    name: "Black Forest cake",
    desc: "Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for will uncover many web sites still in their infancy. Various versions have evolved over the year",
    price: "90",
    Button: "Add to cart",
    img: "https://images.unsplash.com/photo-1582602248706-ddb12de0e625?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=387&q=80",
  },
];
